http:
  port: ${PORT:-8081}
admin:
  port: 9876
  host: localhost
apiEndpoints:
  pitstop-customer:
    host: customer-container
    paths: '/api/customers/*'
  pitstop-vehicle:
    host: vehicle-container
    paths: '/api/vehicles/*'
  pitstop-workshop:
    host: workshop-container
    paths: '/api/workshop/*'
serviceEndpoints:
  pitstop-customer-service:
    url: ${CUSTOMER_URL:-'http://customer-container:3000'}
  pitstop-vehicle-service:
    url: ${VEHICLE_URL:-'http://vehicle-container:3001'}
  pitstop-workshop-service:
    url: ${WORKSHOP_URL:-'http://workshop-container:3002'}

policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  customers-pipelines:
    apiEndpoints:
      - pitstop-customer
    policies:
      - proxy:
          - action:
              serviceEndpoint: pitstop-customer-service
              changeOrigin: true
  vehicles-pipelines:
    apiEndpoints:
      - pitstop-vehicle
    policies:
      - proxy:
          - action:
              serviceEndpoint: pitstop-vehicle-service
              changeOrigin: true
  workshop-pipelines:
    apiEndpoints:
      - pitstop-workshop
    policies:
      - proxy:
          - action:
              serviceEndpoint: pitstop-workshop-service
              changeOrigin: true
